### ISSUE TITLE
High-level Feedback for Descriptive Writing

### ISSUE THREAD

**Issue by boyulz** [JadnjungSpector/Campus_Newbie#12]
The README for Campus Newbie is well-structured and detailed, offering clear instructions for installation, usage, and development. It effectively outlines prerequisites, functionality, and testing, making it accessible to both users and contributors. The inclusion of a directory structure and external tool links adds value, ensuring a smooth setup process. Its focus on both frontend and backend instructions is a strong point, catering to diverse technical needs.

However, the introduction lacks an engaging hook to highlight the platform’s unique features, and some sections, like installation, are overly technical and may overwhelm new developers. The tone is inconsistent, shifting between formal and conversational, and the "Known Bugs" section could provide more immediate insights rather than directing users elsewhere. Simplifying complex steps and maintaining a consistent style would make the README more user-friendly and engaging

**Comment by brigit-parrish** [comment]
Completely agree! I like the suggestion of a known bugs and simplifying the Readme
