### ISSUE TITLE
Missing directories

### ISSUE THREAD

**Issue by boyulz** [JadnjungSpector/Campus_Newbie#5]
Some directories mentioned, like Campus_Newbie/CampusNewbie/src/main and Campus_Newbie/CampusNewbie/src/test, are not present in the actual project. So I would suggest verify and update the directory structure to accurately reflect the existing files and folders.

**Comment by brigit-parrish** [comment]
Thank you this was an issue we were having because of outdated readme and improper pulling and pushing! https://github.com/JadnjungSpector/Campus_Newbie/pull/21
