### ISSUE TITLE
Poorly structured code sections

### ISSUE THREAD

**Issue by boyulz** [JadnjungSpector/Campus_Newbie#6]
The guideline includes many code examples that are not formatted well, making them hard to read. 
Suggestion:
Wrap code in triple backticks (```) with language indicators like bash or json.
Add indentation and spacing for clarity.

**Comment by brigit-parrish** [comment]
Thank you we got rid of that and took in ur suggestions: https://github.com/JadnjungSpector/Campus_Newbie/pull/21
