### ISSUE TITLE
Disorganized Sections

### ISSUE THREAD

**Issue by boyulz** [JadnjungSpector/Campus_Newbie#7]
Splitting the README into user and developer sections while including installation steps in both is confusing.
Suggestion: Reorganize into a logical flow:
Project information and setup at the top, covering prerequisites and installation for both backend and frontend.
Separate user and developer sections, focusing on their respective instructions.
Once the website is live, move troubleshooting to the developer section, but for now, include it for users as well.

**Comment by brigit-parrish** [comment]
Thank you so much for this tip! we will follow this
